Repository Py-KMS-Organization/py-kms, pull requests merged in 2024-05, with the labels that each got.

#96 Apply patch from hyperboreanwolfgirl for Windows Server 2022
  py-kms/KmsDataBase.xml
Labels: enhancement, fix

#110 Minor update
  README.md
  docker/docker-py3-kms-minimal/requirements.txt
  docker/docker-py3-kms/requirements.txt
  docs/Getting Started.md
  py-kms/KmsDataBase.xml
  py-kms/pykms_Server.py
Labels: documentation, fix

#114 Fix dualstack-introduced issues
  docker/docker-py3-kms-minimal/Dockerfile
  docker/docker-py3-kms/Dockerfile
  docker/start.py
  docs/Usage.md
  py-kms/pykms_Server.py
Labels: bug, documentation, confirmed
